[package]
name = "newokvs"
version = "0.1.1"
edition = "2021"


[dependencies]
blake3 = "1.3.3"
aes = "0.8.2"
rand = "0.8.5"
lazy_static = "1.4.0"
num-traits = "0.2.17"
clap = { version = "4.4.7", features = ["derive"] }
rand_chacha = "0.3.1"
num_cpus = "1.13"